---

# REQUIRED !!!
#clusterName: ""
#clientID: ""
#clientSecret: ""

csi:
  image:
    repository: owps/csi-oktawave
    tag: t14

registrar:
  image:
    repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    tag: v2.5.0

provisioner:
  image:
    repository: k8s.gcr.io/sig-storage/csi-provisioner
    tag: v3.1.0

attacher:
  image:
    repository: k8s.gcr.io/sig-storage/csi-attacher
    tag: v3.4.0

resizer:
  image:
    repository: k8s.gcr.io/sig-storage/csi-resizer
    tag: v1.4.0

