---

# REQUIRED !!!
#clusterName: ""
#clientID: ""
#clientSecret: ""

# Warszawa
oktawaveApiEndpoint: "https://pl1-api.oktawave.com/services"
# Skawina
# oktawaveApiEndpoint: "https://pl2-api.oktawave.com/services"

csi:
  image:
    repository: owps/csi-oktawave
    tag: t20

registrar:
  image:
    repository: k8s.gcr.io/sig-storage/csi-node-driver-registrar
    tag: v2.7.0

provisioner:
  image:
    repository: k8s.gcr.io/sig-storage/csi-provisioner
    tag: v3.4.0

attacher:
  image:
    repository: k8s.gcr.io/sig-storage/csi-attacher
    tag: v4.2.0

resizer:
  image:
    repository: k8s.gcr.io/sig-storage/csi-resizer
    tag: v1.7.0


installStorageClassess: true
