---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oktawave-csi.fullname" . }}
data:
  ACCESS_CREDENTIALS: {{ printf "%s:%s" .Values.clientID .Values.clientSecret | b64enc }}
  CLUSTER_NAME: {{ .Values.clusterName | b64enc }}
  OKTAWAVE_API_ENDPOINT: {{ .Values.oktawaveApiEndpoint | b64enc }}
