---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ include "oktawave-csi.fullname" . }}-controller
spec:
  selector:
    matchLabels:
      app: {{ include "oktawave-csi.fullname" . }}-controller
      role: csi
  serviceName: csi
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "oktawave-csi.fullname" . }}-controller
        role: csi
    spec:
      serviceAccount: {{ include "oktawave-csi.fullname" . }}-controller
      containers:
        - name: csi-provisioner
          image: {{ .Values.provisioner.image.repository }}:{{ .Values.provisioner.image.tag }}
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
            - "--strict-topology=true"
            - "--feature-gates=Topology=true"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-attacher
          image: {{ .Values.attacher.image.repository }}:{{ .Values.attacher.image.tag }}
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-resizer
          image: {{ .Values.resizer.image.repository }}:{{ .Values.resizer.image.tag }}
          args:
            - "--csi-address=$(ADDRESS)"
            - "--v=5"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
        - name: csi-plugin
          image: {{ .Values.csi.image.repository }}:{{ .Values.csi.image.tag }}
          command: ["/usr/local/bin/csi-oktawave"]
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --clusterName=$(CLUSTER_NAME)
            - --token=$(ACCESS_TOKEN)
            - --credentials=$(ACCESS_CREDENTIALS)
            - --skipTLS=true
          envFrom:
          - secretRef:
              name: {{ include "oktawave-csi.fullname" . }}
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: ACCESS_TOKEN
              value: "OBSOLETE"
          imagePullPolicy: "Always"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: 8080
      volumes:
        - name: socket-dir
          emptyDir: {}
